global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/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

route:
  group_by: ['alertname']
  group_wait: 2m
  group_interval: 5m
  repeat_interval: 1h

  # If an alert isn't caught by a route, send it to slack.
  receiver: slack_and_dingtalk
  routes:
    - match:
        alertname: Watchdog
      receiver: "null"

receivers:
  - name: "null"
  - name: slack_and_dingtalk
    webhook_configs:
    - send_resolved: true
      url: http://prometheus-webhook-dingtalk.kubeaddons.svc.cluster.local:8060/dingtalk/webhook1/send
    slack_configs:
      - channel: '#k8s'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '{{ template "slack.default.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        pretext: '{{ template "slack.default.pretext" . }}'
        text: '{{ template "slack.default.text" . }}'
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'

templates:
  - '*.tmpl'